### ISSUE TITLE
Support for multiple install targets

### ISSUE THREAD

**Issue by austince** [tamayika/types-local#1]
What do you think about allowing for multiple arguments to be passed into the `install` command? 

Like so:
`types-local install mocha chai rimraf`

Would be happy to submit a PR.

**Comment by tamayika** [comment]
Sorry for the late response.
It is nice to support multiple modules.
If you make a PR, I will review and merge it.

**Comment by tamayika** [comment]
Sorry, I made a PR and merged it.
