### ISSUE TITLE
Support custom install location

### ISSUE THREAD

**Issue by austince** [tamayika/types-local#2]
Support configuration for the installation location. Could go in tsconfig?

Like:
tsconfig.json
```json
{
  "compilerOptions": {
   ...
   },
   ...
   "types-local": {
      "installDir": "lib/types"
   } 
}
```

**Comment by tamayika** [comment]
I don't think it is nice to write setting in tsconfig.json. 
I think another file like types-local.json would be nice.

types-local.json
```json
{
  "installDir": "lib/types"
}
```
